package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestConfigContractCheckerRejectsMissingRuntimeConsumer(t *testing.T) {
	tests := []struct {
		name       string
		consumer   string
		wantFailed bool
	}{
		{name: "consumer present", consumer: `package app; import "github.com/fdefilippo/resman/config"; func use(c *config.Config) { _ = c.GetValue() }`},
		{name: "consumer missing despite unrelated selector", consumer: `package app; type other struct{ Value string }; func use(o other) { _ = o.Value }`, wantFailed: true},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			root := newCheckerFixture(t)
			writeFixture(t, root, "config/config.go", `package config
import "fmt"
type Config struct { Value string `+"`config:\"VALUE\"`"+` }
type handler func(*Config, string) error
var configFieldHandlers = map[string]handler{"VALUE": func(c *Config, value string) error { c.Value = value; return nil }}
func setConfigField(c *Config, key, value string) error { h, ok := configFieldHandlers[key]; if !ok { return fmt.Errorf("unknown configuration key %q", key) }; return h(c, value) }
func (c *Config) GetValue() string { return c.Value }
`)
			writeFixture(t, root, "app/app.go", tt.consumer)
			writeFixture(t, root, "scripts/verify-contracts/config-consumers.allowlist", "# empty\n")
			sources, parseFindings := loadGoFiles(root)
			if len(parseFindings) != 0 {
				t.Fatalf("parse findings: %v", parseFindings)
			}
			result := checkConfigContracts(root, sources)
			if got := len(result.findings) > 0; got != tt.wantFailed {
				t.Fatalf("failed = %v, want %v; findings=%v", got, tt.wantFailed, result.findings)
			}
		})
	}
}

func TestPrometheusCallSiteCheckerRejectsRegisteredButUnusedMetric(t *testing.T) {
	tests := []struct {
		name       string
		update     string
		wantFailed bool
	}{
		{name: "updated", update: `func (exp *Exporter) update() { exp.requests.Inc() }`},
		{name: "read but not updated", update: `func (exp *Exporter) inspect() { _ = exp.requests }`, wantFailed: true},
		{name: "not updated", wantFailed: true},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			root := newCheckerFixture(t)
			writeFixture(t, root, "metrics/prometheus.go", `package metrics
type metric interface{ Inc() }
type Exporter struct{ requests metric }
type factory struct{}
func (factory) NewCounter(any) metric { return nil }
var prometheusFactory factory
func (exp *Exporter) registerMetrics() { exp.requests = prometheusFactory.NewCounter(struct{}{}) }
`+tt.update)
			sources, _ := loadGoFiles(root)
			result := checkPrometheusCallSites(sources)
			if got := len(result.findings) > 0; got != tt.wantFailed {
				t.Fatalf("failed = %v, want %v; findings=%v", got, tt.wantFailed, result.findings)
			}
		})
	}
}

func TestSleepCheckerRequiresExplicitNonStaleClassification(t *testing.T) {
	tests := []struct {
		name       string
		allowlist  string
		wantFailed bool
	}{
		{name: "allowed", allowlist: "app/app.go | retry | 1 | bounded retry | allowed | Backoff after a failed operation.\n"},
		{name: "unlisted", allowlist: "# empty\n", wantFailed: true},
		{name: "stale", allowlist: "app/app.go | other | 1 | bounded retry | allowed | Wrong function.\n", wantFailed: true},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			root := newCheckerFixture(t)
			writeFixture(t, root, "app/app.go", `package app; import "time"; func retry(){ time.Sleep(time.Second) }`)
			writeFixture(t, root, "scripts/verify-contracts/time-sleep.allowlist", tt.allowlist)
			writeFixture(t, root, "scripts/verify-contracts/time-sleep.known", "# empty\n")
			sources, _ := loadGoFiles(root)
			result := checkProductionSleeps(root, sources)
			if got := len(result.findings) > 0; got != tt.wantFailed {
				t.Fatalf("failed = %v, want %v; findings=%v", got, tt.wantFailed, result.findings)
			}
		})
	}
}

func TestLockBoundaryInventoryCheckerRequiresExactProductionCoverage(t *testing.T) {
	tests := []struct {
		name          string
		inventoryRows string
		allowlist     string
		wantFragment  string
	}{
		{
			name:          "complete inventory",
			inventoryRows: "| App | `app.Config`<br>`app.Runner`<br>`app.Worker` | state | gate | reviewed |\n",
		},
		{
			name:          "classified exception",
			inventoryRows: "| App | `app.Config`<br>`app.Worker` | state | gate | reviewed |\n",
			allowlist:     "app.Runner | runGate:operationgate.Gate | allowed | The boundary is generated by an external contract.\n",
		},
		{
			name:          "missing entry reports type and field",
			inventoryRows: "| App | `app.Config`<br>`app.Worker` | state | gate | reviewed |\n",
			wantFragment:  "synchronization-bearing type app.Runner is missing",
		},
		{
			name:          "duplicate entry",
			inventoryRows: "| App | `app.Config`<br>`app.Config`<br>`app.Runner`<br>`app.Worker` | state | gate | reviewed |\n",
			wantFragment:  "duplicate lock-boundary inventory entry for app.Config",
		},
		{
			name:          "stale entry",
			inventoryRows: "| App | `app.Config`<br>`app.Gone`<br>`app.Runner`<br>`app.Worker` | state | gate | reviewed |\n",
			wantFragment:  "stale lock-boundary inventory entry for app.Gone",
		},
		{
			name:          "stale exception",
			inventoryRows: "| App | `app.Config`<br>`app.Runner`<br>`app.Worker` | state | gate | reviewed |\n",
			allowlist:     "app.Gone | mu:sync.Mutex | allowed | Generated elsewhere.\n",
			wantFragment:  "stale allowlist entry",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			root := newCheckerFixture(t)
			writeFixture(t, root, "app/app.go", `package app
import (
    s "sync"
    gate "github.com/fdefilippo/resman/internal/operationgate"
)
type Config struct { mu s.Mutex }
type Worker struct { mu s.RWMutex }
type Runner struct { runGate *gate.Gate }
`)
			writeFixture(t, root, "app/app_test.go", `package app; import "sync"; type testOnly struct { mu sync.Mutex }`)
			writeFixture(t, root, "app/generated.go", `// Code generated by fixture. DO NOT EDIT.
package app
import "sync"
type generatedOnly struct { mu sync.Mutex }
`)
			writeFixture(t, root, lockBoundaryInventoryPath, `# Lock-boundary inventory
| Component | Synchronization-bearing types | State synchronization | Ordered-operation gate | Reviewed boundary |
| --- | --- | --- | --- | --- |
`+tt.inventoryRows)
			writeFixture(t, root, lockBoundaryAllowlistPath, "# exceptions\n"+tt.allowlist)
			sources, parseFindings := loadGoFiles(root)
			if len(parseFindings) != 0 {
				t.Fatalf("parse findings: %v", parseFindings)
			}
			result := checkLockBoundaryInventory(root, sources)
			if tt.wantFragment == "" {
				if len(result.findings) != 0 {
					t.Fatalf("unexpected findings: %v", result.findings)
				}
				return
			}
			for _, item := range result.findings {
				if strings.Contains(item.message, tt.wantFragment) {
					if tt.name == "missing entry reports type and field" && (!strings.Contains(item.message, "runGate:operationgate.Gate") || item.path != "app/app.go") {
						t.Fatalf("missing-entry diagnostic lacks file/type/field: %+v", item)
					}
					return
				}
			}
			t.Fatalf("finding containing %q not found: %v", tt.wantFragment, result.findings)
		})
	}
}

func TestCrossPackageMapKeyCheckerReportsLiteralBoundary(t *testing.T) {
	tests := []struct {
		name        string
		consumerKey string
		known       string
		wantFailed  bool
		wantKnown   bool
	}{
		{name: "typed or distinct", consumerKey: "other"},
		{name: "untracked duplicate", consumerKey: "path", wantFailed: true},
		{name: "tracked duplicate", consumerKey: "path", known: "path | cgroup,mcp | known | resman-test.1 owns the typed replacement.\n", wantKnown: true},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			root := newCheckerFixture(t)
			writeFixture(t, root, "cgroup/info.go", `package cgroup; func produce(m map[string]string){ _ = m["path"] }`)
			writeFixture(t, root, "mcp/info.go", `package mcp; func consume(m map[string]string){ _ = m["`+tt.consumerKey+`"] }`)
			writeFixture(t, root, "scripts/verify-contracts/cross-package-map-keys.allowlist", "# empty\n")
			writeFixture(t, root, "scripts/verify-contracts/cross-package-map-keys.known", "# known\n"+tt.known)
			sources, _ := loadGoFiles(root)
			result := checkCrossPackageMapKeys(root, sources)
			if got := len(result.findings) > 0; got != tt.wantFailed {
				t.Fatalf("failed = %v, want %v; findings=%v", got, tt.wantFailed, result.findings)
			}
			if got := len(result.notices) > 0; got != tt.wantKnown {
				t.Fatalf("known = %v, want %v; notices=%v", got, tt.wantKnown, result.notices)
			}
		})
	}
}

func TestCrossPackageMapKeyCheckerReportsCompositeLiteralBoundary(t *testing.T) {
	root := newCheckerFixture(t)
	writeFixture(t, root, "cgroup/info.go", `package cgroup; func produce() map[string]string { return map[string]string{"path": "/sys/fs/cgroup/user"} }`)
	writeFixture(t, root, "mcp/info.go", `package mcp; func consume() map[string]any { return map[string]any{"path": "visible"} }`)
	writeFixture(t, root, "scripts/verify-contracts/cross-package-map-keys.allowlist", "# empty\n")
	writeFixture(t, root, "scripts/verify-contracts/cross-package-map-keys.known", "# empty\n")
	sources, _ := loadGoFiles(root)
	result := checkCrossPackageMapKeys(root, sources)
	if len(result.findings) != 2 {
		t.Fatalf("findings = %d, want 2; findings=%v", len(result.findings), result.findings)
	}
	for _, item := range result.findings {
		if item.line != 1 || !strings.Contains(item.message, `string map key "path" is duplicated across packages cgroup,mcp`) {
			t.Fatalf("unexpected finding: %+v", item)
		}
	}
}

func TestMCPCheckerPinsSDKRevisionAndStatelessTransport(t *testing.T) {
	tests := []struct {
		name       string
		sdk        string
		revision   string
		stateless  string
		wantFailed bool
	}{
		{name: "current", sdk: "v1.7.0", revision: "2026-07-28", stateless: "true"},
		{name: "old sdk", sdk: "v1.6.9", revision: "2026-07-28", stateless: "true", wantFailed: true},
		{name: "prerelease sdk", sdk: "v1.7.0-rc.1", revision: "2026-07-28", stateless: "true", wantFailed: true},
		{name: "old revision", sdk: "v1.7.0", revision: "2025-11-25", stateless: "true", wantFailed: true},
		{name: "stateful", sdk: "v1.7.0", revision: "2026-07-28", stateless: "false", wantFailed: true},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			root := newCheckerFixture(t)
			writeFixture(t, root, "go.mod", "module example.test/checker\n\ngo 1.25.7\n\nrequire github.com/modelcontextprotocol/go-sdk "+tt.sdk+"\n")
			writeFixture(t, root, "mcp/server.go", `package mcp
const protocolVersion = "`+tt.revision+`"
type StreamableHTTPOptions struct{ Stateless bool }
func serve(){ _ = sdk.StreamableHTTPOptions{Stateless: `+tt.stateless+`} }
var sdk struct{ StreamableHTTPOptions StreamableHTTPOptions }
`)
			writeFixture(t, root, "scripts/verify-contracts/mcp-literals.allowlist", "# empty\n")
			sources, parseFindings := loadGoFiles(root)
			if len(parseFindings) != 0 {
				t.Fatalf("parse findings: %v", parseFindings)
			}
			result := checkMCPContracts(root, sources)
			if got := len(result.findings) > 0; got != tt.wantFailed {
				t.Fatalf("failed = %v, want %v; findings=%v", got, tt.wantFailed, result.findings)
			}
		})
	}
}

func TestMCPCheckerRejectsMCPGoDebugOutsideMCPPackage(t *testing.T) {
	root := newCheckerFixture(t)
	writeFixture(t, root, "go.mod", "module example.test/checker\n\ngo 1.25.7\n\nrequire github.com/modelcontextprotocol/go-sdk v1.7.0\n")
	writeFixture(t, root, "mcp/server.go", `package mcp
const protocolVersion = "2026-07-28"
type StreamableHTTPOptions struct{ Stateless bool }
func serve(){ _ = sdk.StreamableHTTPOptions{Stateless: true} }
var sdk struct{ StreamableHTTPOptions StreamableHTTPOptions }
`)
	writeFixture(t, root, "internal/app/debug.go", `package app; const compatibilityEnvironment = "MCPGODEBUG=legacy"`)
	writeFixture(t, root, "scripts/verify-contracts/mcp-literals.allowlist", "# empty\n")
	sources, _ := loadGoFiles(root)
	result := checkMCPContracts(root, sources)
	if len(result.findings) == 0 {
		t.Fatal("MCPGODEBUG outside package mcp was not rejected")
	}
}

func TestShippedAssetCheckerRejectsTokensAndStaleAllowlist(t *testing.T) {
	tests := []struct {
		name       string
		path       string
		content    string
		allowlist  string
		wantFailed bool
	}{
		{name: "clean", content: "ResMan listens on 1974.\n"},
		{name: "stale token", content: "Copy CPU Manager configuration.\n", wantFailed: true},
		{name: "plural product name", content: "The CPU Managers are legacy.\n", wantFailed: true},
		{name: "mixed-case product name", content: "Copy cPu MaNaGeR configuration.\n", wantFailed: true},
		{name: "uppercase configuration namespace", content: "CPU_MANAGER_BLACKOUT was the historical key.\n", wantFailed: true},
		{name: "classified uppercase configuration namespace", content: "CPU_MANAGER_BLACKOUT was the historical key.\n", allowlist: "docs/example.md | CPU_MANAGER | CPU_MANAGER_BLACKOUT | historical configuration key | allowed | This exact historical key is part of the version record.\n"},
		{name: "changelog-like path is scanned", path: "docs/changelog-notes.md", content: "Copy CPU Manager configuration.\n", wantFailed: true},
		{name: "RPM changelog is historical", path: "packaging/example.spec", content: "%changelog\n- CPU Manager was the former product name.\n"},
		{name: "allowed provenance", content: "The old port was 9101.\n", allowlist: "docs/example.md | 9101 | old port was 9101 | provenance | allowed | Historical audit provenance.\n"},
		{name: "stale allowlist", content: "ResMan listens on 1974.\n", allowlist: "docs/example.md | 9101 | old port was 9101 | provenance | allowed | Historical audit provenance.\n", wantFailed: true},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			root := newCheckerFixture(t)
			path := tt.path
			if path == "" {
				path = "docs/example.md"
			}
			writeFixture(t, root, path, tt.content)
			writeFixture(t, root, "docs/empty", "")
			writeFixture(t, root, "packaging/empty", "")
			writeFixture(t, root, "scripts/verify-contracts/shipped-assets.allowlist", "# allowed\n"+tt.allowlist)
			writeFixture(t, root, "scripts/verify-contracts/shipped-assets.known", "# known\n")
			writeFixture(t, root, "README.md", "ResMan\n")
			writeFixture(t, root, "CONTRIBUTING.md", "ResMan\n")
			sources, parseFindings := loadGoFiles(root)
			if len(parseFindings) != 0 {
				t.Fatalf("parse findings: %v", parseFindings)
			}
			result := checkShippedAssets(root, sources)
			if got := len(result.findings) > 0; got != tt.wantFailed {
				t.Fatalf("failed = %v, want %v; findings=%v", got, tt.wantFailed, result.findings)
			}
		})
	}
}

func TestShippedAssetCheckerRejectsObsoleteProductNamesInProductionGo(t *testing.T) {
	tests := []struct {
		name       string
		path       string
		content    string
		allowlist  string
		wantFailed bool
		wantLine   int
	}{
		{
			name:       "string literal",
			content:    "package app\n\nconst description = \"Get CPU Manager configuration\"\n",
			wantFailed: true,
			wantLine:   3,
		},
		{
			name:       "comment",
			content:    "package app\n\n// CPU-Manager applies limits.\nfunc apply() {}\n",
			wantFailed: true,
			wantLine:   3,
		},
		{
			name:       "mixed-case comment",
			content:    "package app\n\n// cPu_mAnAgEr was the old namespace.\nfunc apply() {}\n",
			wantFailed: true,
			wantLine:   3,
		},
		{
			name:       "concatenated string literal",
			content:    "package app\n\nconst description = \"CPUManager legacy name\"\n",
			wantFailed: true,
			wantLine:   3,
		},
		{
			name:       "concatenated type identifier",
			content:    "package app\n\ntype CPUManager struct{}\n",
			wantFailed: true,
			wantLine:   3,
		},
		{
			name:       "prefixed concatenated identifier",
			content:    "package app\n\nfunc NewCPUManager() {}\n",
			wantFailed: true,
			wantLine:   3,
		},
		{
			name:       "suffixed concatenated type identifier",
			content:    "package app\n\ntype CPUManagerFactory struct{}\n",
			wantFailed: true,
			wantLine:   3,
		},
		{
			name:       "suffixed camel-case identifier",
			content:    "package app\n\nfunc cpuManagerService() {}\n",
			wantFailed: true,
			wantLine:   3,
		},
		{
			name:      "classified uppercase configuration identifier",
			content:   "package app\n\nconst historicalKey = \"CPU_MANAGER_BLACKOUT\"\n",
			allowlist: "app/app.go | CPU_MANAGER | CPU_MANAGER_BLACKOUT | historical configuration key | allowed | This exact historical key is retained as explicit provenance.\n",
		},
		{
			name:    "test source is excluded",
			path:    "app/app_test.go",
			content: "package app\n\nconst obsoleteFixture = \"CPU Manager\"\n",
		},
		{
			name:    "checker source is self-excluded",
			path:    "scripts/verify-contracts/self.go",
			content: "package main\n\nconst forbiddenPattern = \"CPU Manager\"\n",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			root := newCheckerFixture(t)
			path := tt.path
			if path == "" {
				path = "app/app.go"
			}
			writeFixture(t, root, path, tt.content)
			writeFixture(t, root, "docs/example.md", "ResMan\n")
			writeFixture(t, root, "packaging/empty", "")
			writeFixture(t, root, "scripts/verify-contracts/shipped-assets.allowlist", "# allowed\n"+tt.allowlist)
			writeFixture(t, root, "scripts/verify-contracts/shipped-assets.known", "# known\n")
			writeFixture(t, root, "README.md", "ResMan\n")
			writeFixture(t, root, "CONTRIBUTING.md", "ResMan\n")

			sources, parseFindings := loadGoFiles(root)
			if len(parseFindings) != 0 {
				t.Fatalf("parse findings: %v", parseFindings)
			}
			result := checkShippedAssets(root, sources)
			if got := len(result.findings) > 0; got != tt.wantFailed {
				t.Fatalf("failed = %v, want %v; findings=%v", got, tt.wantFailed, result.findings)
			}
			if tt.wantFailed && (len(result.findings) != 1 || result.findings[0].path != path || result.findings[0].line != tt.wantLine) {
				t.Fatalf("unexpected finding location: %+v", result.findings)
			}
		})
	}
}

func TestShippedAssetCheckerIgnoresUntrackedWorkspaceFiles(t *testing.T) {
	root := newCheckerFixture(t)
	writeFixture(t, root, "docs/example.md", "ResMan\n")
	writeFixture(t, root, "docs/analysis/local.md", "CPU Manager was a local analysis note.\n")
	writeFixture(t, root, "app/local.go", "package app\n\nconst localNote = \"CPU_MANAGER_LOCAL\"\n")
	writeFixture(t, root, "packaging/empty", "")
	writeFixture(t, root, "scripts/verify-contracts/shipped-assets.allowlist", "# allowed\n")
	writeFixture(t, root, "scripts/verify-contracts/shipped-assets.known", "# known\n")
	writeFixture(t, root, "README.md", "ResMan\n")
	writeFixture(t, root, "CONTRIBUTING.md", "ResMan\n")

	sources, parseFindings := loadGoFiles(root)
	if len(parseFindings) != 0 {
		t.Fatalf("parse findings: %v", parseFindings)
	}
	tracked := map[string]bool{
		"docs/example.md": true,
		"packaging/empty": true,
		"README.md":       true,
		"CONTRIBUTING.md": true,
	}
	result := checkShippedAssetsWithTrackedPaths(root, sources, tracked)
	if len(result.findings) != 0 {
		t.Fatalf("untracked workspace files produced findings: %v", result.findings)
	}
}

func TestEnglishLanguageCheckerRejectsProductionCommentsAndCurrentDocumentation(t *testing.T) {
	tests := []struct {
		name       string
		goSource   string
		document   string
		debHistory string
		rpmHistory string
		wantPath   string
		wantLine   int
	}{
		{
			name:     "English production text",
			goSource: "package app\n\n// Apply updates the active policy.\nfunc Apply() {}\n",
			document: "# Operator guide\n\nConfigure the service before starting it.\n",
		},
		{
			name:     "Italian production comment",
			goSource: "package app\n\n// Apply aggiorna la configurazione attiva.\nfunc Apply() {}\n",
			document: "# Operator guide\n",
			wantPath: "app/app.go",
			wantLine: 3,
		},
		{
			name:     "Italian shipped paragraph",
			goSource: "package app\n\nfunc Apply() {}\n",
			document: "# Operator guide\n\nVerifica la configurazione prima di avviare il servizio.\n",
			wantPath: "docs/example.md",
			wantLine: 3,
		},
		{
			name:       "Historical changelogs are preserved",
			goSource:   "package app\n\nfunc Apply() {}\n",
			document:   "# Operator guide\n",
			debHistory: "resman (1.0) stable; urgency=low\n\n  * Aggiunta configurazione iniziale.\n",
			rpmHistory: "%changelog\n* Thu Aug 28 2026 Maintainer\n- Aggiunta configurazione iniziale.\n",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			root := newCheckerFixture(t)
			writeFixture(t, root, "app/app.go", tt.goSource)
			writeFixture(t, root, "docs/example.md", tt.document)
			writeFixture(t, root, "packaging/empty", "")
			if tt.debHistory != "" {
				writeFixture(t, root, "packaging/deb/changelog", tt.debHistory)
			}
			if tt.rpmHistory != "" {
				writeFixture(t, root, "packaging/example.spec", tt.rpmHistory)
			}
			writeFixture(t, root, "scripts/empty", "")
			writeFixture(t, root, "README.md", "ResMan\n")
			writeFixture(t, root, "CONTRIBUTING.md", "ResMan\n")
			writeFixture(t, root, "Makefile", "help:\n\t@echo ResMan\n")
			sources, parseFindings := loadGoFiles(root)
			if len(parseFindings) != 0 {
				t.Fatalf("parse findings: %v", parseFindings)
			}
			result := checkEnglishLanguage(root, sources)
			if tt.wantPath == "" {
				if len(result.findings) != 0 {
					t.Fatalf("unexpected findings: %v", result.findings)
				}
				return
			}
			if len(result.findings) == 0 {
				t.Fatal("Italian production text was not rejected")
			}
			if result.findings[0].path != tt.wantPath || result.findings[0].line != tt.wantLine {
				t.Fatalf("unexpected finding location: %+v", result.findings[0])
			}
		})
	}
}

func TestEnglishLanguageCheckerScansPackagingSyslog(t *testing.T) {
	root := newCheckerFixture(t)
	writeFixture(t, root, "docs/empty", "")
	writeFixture(t, root, "packaging/syslog/resman", "# Ricarica rsyslog dopo la rotazione")
	writeFixture(t, root, "scripts/empty", "")
	writeFixture(t, root, "README.md", "ResMan")
	writeFixture(t, root, "CONTRIBUTING.md", "ResMan")
	writeFixture(t, root, "Makefile", "help:\n\t@echo ResMan")
	sources, parseFindings := loadGoFiles(root)
	if len(parseFindings) != 0 {
		t.Fatalf("parse findings: %v", parseFindings)
	}
	tracked := map[string]bool{
		"docs/empty":              true,
		"packaging/syslog/resman": true,
		"scripts/empty":           true,
		"README.md":               true,
		"CONTRIBUTING.md":         true,
		"Makefile":                true,
	}
	result := checkEnglishLanguageWithTrackedPaths(root, sources, tracked)
	if len(result.findings) != 1 {
		t.Fatalf("expected one Italian packaging finding, got %v", result.findings)
	}
	if result.findings[0].path != "packaging/syslog/resman" || result.findings[0].line != 1 {
		t.Fatalf("unexpected finding location: %+v", result.findings[0])
	}
}

func TestSystemdUnitMutationBoundaryRejectsEverySideDoor(t *testing.T) {
	tests := []struct {
		name       string
		path       string
		content    string
		wantFailed bool
	}{
		{
			name:    "authoritative adapter runtime mutation",
			path:    systemdUnitAdapterPath,
			content: `package systemdunit; type connection struct{}; func (connection) SetUnitPropertiesContext(...any){}; func apply(c connection){ c.SetUnitPropertiesContext(nil, "user.slice", true) }`,
		},
		{
			name:       "raw systemd-owned cgroup path",
			path:       "state/apply.go",
			content:    `package state; const target = "/sys/fs/cgroup/user.slice/user-1000.slice/cpu.weight"`,
			wantFailed: true,
		},
		{
			name:       "direct systemd mutation outside adapter",
			path:       "state/apply.go",
			content:    `package state; type connection struct{}; func (connection) SetUnitPropertiesContext(...any){}; func apply(c connection){ c.SetUnitPropertiesContext(nil, "unit", true) }`,
			wantFailed: true,
		},
		{
			name:       "deprecated direct systemd mutation outside adapter",
			path:       "state/apply.go",
			content:    `package state; type connection struct{}; func (connection) SetUnitProperties(...any){}; func apply(c connection){ c.SetUnitProperties("unit", true) }`,
			wantFailed: true,
		},
		{
			name:       "process attachment through systemd",
			path:       "state/apply.go",
			content:    `package state; type connection struct{}; func (connection) AttachProcessesToUnit(...any){}; func apply(c connection){ c.AttachProcessesToUnit(nil, "unit", "/", []uint32{1}) }`,
			wantFailed: true,
		},
		{
			name:       "authoritative control group used outside verifier",
			path:       "state/apply.go",
			content:    `package state; import ("os"; "path/filepath"); type unit struct{ ControlGroup string }; func apply(u unit){ _ = os.WriteFile(filepath.Join("/sys/fs/cgroup", u.ControlGroup, "cpu.weight"), nil, 0600) }`,
			wantFailed: true,
		},
		{
			name:    "authoritative control group used by read-only coverage inspector",
			path:    systemdUnitCoveragePath,
			content: `package systemdunit; type unit struct{ ControlGroup string }; func inspect(u unit){ _ = u.ControlGroup }`,
		},
		{
			name:       "raw manager mutation over D-Bus",
			path:       "state/apply.go",
			content:    `package state; type object struct{}; func (object) Call(...any){}; func apply(o object){ o.Call("org.freedesktop.systemd1.Manager.SetUnitProperties", "unit") }`,
			wantFailed: true,
		},
		{
			name:       "raw D-Bus dependency outside adapter",
			path:       "state/apply.go",
			content:    `package state; import _ "github.com/godbus/dbus/v5"`,
			wantFailed: true,
		},
		{
			name:       "go-systemd dependency outside adapter",
			path:       "state/apply.go",
			content:    `package state; import _ "github.com/coreos/go-systemd/v22/dbus"`,
			wantFailed: true,
		},
		{
			name:    "guarded raw revert inside transport",
			path:    systemdUnitAdapterPath,
			content: `package systemdunit; type object struct{}; func (object) CallWithContext(...any){}; func restore(o object){ o.CallWithContext(nil, "org.freedesktop.systemd1.Manager.RevertUnitFiles", 0, []string{"unit"}) }`,
		},
		{
			name:       "general unit lifecycle method",
			path:       systemdUnitAdapterPath,
			content:    `package systemdunit; type connection struct{}; func (connection) StartUnitContext(...any){}; func apply(c connection){ c.StartUnitContext(nil, "unit") }`,
			wantFailed: true,
		},
		{
			name: "exact empty capability probe lifecycle",
			path: systemdUnitAdapterPath,
			content: `package systemdunit
type connection struct{}
func (connection) StartTransientUnitContext(...any){}
func (connection) StopUnitContext(...any){}
type dbusTransport struct{ conn connection }
func (t *dbusTransport) startCapabilityProbe(){ t.conn.StartTransientUnitContext(nil, "probe.slice") }
func (t *dbusTransport) stopCapabilityProbe(){ t.conn.StopUnitContext(nil, "probe.slice") }`,
		},
		{
			name:       "transient probe start outside exact method",
			path:       systemdUnitAdapterPath,
			content:    `package systemdunit; type connection struct{}; func (connection) StartTransientUnitContext(...any){}; type dbusTransport struct{ conn connection }; func (t *dbusTransport) startWorkload(){ t.conn.StartTransientUnitContext(nil, "workload.scope") }`,
			wantFailed: true,
		},
		{
			name:       "probe stop outside exact receiver",
			path:       systemdUnitAdapterPath,
			content:    `package systemdunit; type connection struct{}; func (connection) StopUnitContext(...any){}; type otherTransport struct{ conn connection }; func (t *otherTransport) stopCapabilityProbe(){ t.conn.StopUnitContext(nil, "probe.slice") }`,
			wantFailed: true,
		},
		{
			name:       "duplicate transient starts in capability probe",
			path:       systemdUnitAdapterPath,
			content:    `package systemdunit; type connection struct{}; func (connection) StartTransientUnitContext(...any){}; type dbusTransport struct{ conn connection }; func (t *dbusTransport) startCapabilityProbe(){ t.conn.StartTransientUnitContext(nil, "one.slice"); t.conn.StartTransientUnitContext(nil, "two.slice") }`,
			wantFailed: true,
		},
		{
			name:       "cgroup write in adapter",
			path:       "internal/systemdunit/kernel.go",
			content:    `package systemdunit; import "os"; func apply(){ _ = os.WriteFile("cpu.weight", nil, 0600) }`,
			wantFailed: true,
		},
		{
			name:    "durable lease journal write",
			path:    systemdUnitJournalPath,
			content: `package systemdunit; import "os"; func persist(path string){ _ = os.WriteFile(path, nil, 0600) }`,
		},
		{
			name:    "read-only unit footprint open",
			path:    systemdUnitFilesPath,
			content: `package systemdunit; import "os"; func inspect(path string){ file, _ := os.OpenFile(path, os.O_RDONLY, 0); if file != nil { _ = file.Close() } }`,
		},
		{
			name:       "unit footprint writer",
			path:       systemdUnitFilesPath,
			content:    `package systemdunit; import "os"; func mutate(path string){ _ = os.WriteFile(path, nil, 0600) }`,
			wantFailed: true,
		},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			root := newCheckerFixture(t)
			writeFixture(t, root, test.path, test.content)
			sources, parseFindings := loadGoFiles(root)
			if len(parseFindings) != 0 {
				t.Fatalf("parse findings: %v", parseFindings)
			}
			result := checkSystemdUnitMutationBoundary(sources)
			if got := len(result.findings) > 0; got != test.wantFailed {
				t.Fatalf("failed = %v, want %v; findings=%v", got, test.wantFailed, result.findings)
			}
		})
	}
}

func newCheckerFixture(t *testing.T) string {
	t.Helper()
	root := t.TempDir()
	writeFixture(t, root, "go.mod", "module example.test/checker\n\ngo 1.25.7\n")
	return root
}

func writeFixture(t *testing.T, root, relative, content string) {
	t.Helper()
	path := filepath.Join(root, filepath.FromSlash(relative))
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		t.Fatalf("create fixture directory: %v", err)
	}
	if err := os.WriteFile(path, []byte(strings.TrimSpace(content)+"\n"), 0600); err != nil {
		t.Fatalf("write fixture %s: %v", relative, err)
	}
}
