#!/bin/sh
set -e

# Automatically added by dh_installsystemd
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "remove" ] &&
    [ -d /run/systemd/system ]; then
    systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section

# Automatically added by dh_installsystemd
if [ "$1" = "purge" ] && [ -x /usr/bin/deb-systemd-helper ]; then
    deb-systemd-helper purge 'resman.service' >/dev/null || true
fi
# End automatically added section

exit 0
