#!/bin/sh
set -e

# Automatically added by dh_installsystemd
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "remove" ] &&
    [ -d /run/systemd/system ]; then
    deb-systemd-invoke stop 'resman.service' >/dev/null || true
fi
# End automatically added section

exit 0
