ARG FUNCTIONAL_BASE_IMAGE

FROM docker.io/library/golang:1.25.7-bookworm AS builder

WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY main.go ./
COPY cgroup ./cgroup
COPY config ./config
COPY database ./database
COPY internal ./internal
COPY logging ./logging
COPY mcp ./mcp
COPY metrics ./metrics
COPY reloader ./reloader
COPY state ./state
RUN CGO_ENABLED=1 go build -trimpath \
    -ldflags="-s -w -X 'main.version=functional'" \
    -o /out/resman ./main.go

FROM ${FUNCTIONAL_BASE_IMAGE}

COPY --from=builder /out/resman /usr/bin/resman
COPY test/functional/smolvm/guest/resman-functional@.service \
     /usr/lib/systemd/system/resman-functional@.service
COPY test/functional/smolvm/guest/run-functional.sh \
     test/functional/smolvm/guest/assert-daemon-errors.sh \
     test/functional/smolvm/guest/wait-systemd.sh \
     test/functional/smolvm/guest/workload.sh \
     /opt/resman-functional/
COPY test/functional/smolvm/fixtures/resman.conf \
     /opt/resman-functional/fixtures/resman.conf

RUN chmod 0755 /usr/bin/resman \
      /opt/resman-functional/run-functional.sh \
      /opt/resman-functional/assert-daemon-errors.sh \
      /opt/resman-functional/wait-systemd.sh \
      /opt/resman-functional/workload.sh
